// Code generated by MockGen. DO NOT EDIT.
// Source: ./core/ports.go
//
// Generated by this command:
//
//	mockgen -source=./core/ports.go -destination=./core/mocks/mock.go
//

// Package mock_core is a generated GoMock package.
package mock_core

import (
	context "context"
	reflect "reflect"

	core "github.com/Razzle131/dungeon-challenge/core"
	gomock "go.uber.org/mock/gomock"
)

// MockEventReader is a mock of EventReader interface.
type MockEventReader struct {
	ctrl     *gomock.Controller
	recorder *MockEventReaderMockRecorder
	isgomock struct{}
}

// MockEventReaderMockRecorder is the mock recorder for MockEventReader.
type MockEventReaderMockRecorder struct {
	mock *MockEventReader
}

// NewMockEventReader creates a new mock instance.
func NewMockEventReader(ctrl *gomock.Controller) *MockEventReader {
	mock := &MockEventReader{ctrl: ctrl}
	mock.recorder = &MockEventReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventReader) EXPECT() *MockEventReaderMockRecorder {
	return m.recorder
}

// GetNextEvent mocks base method.
func (m *MockEventReader) GetNextEvent() (core.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextEvent")
	ret0, _ := ret[0].(core.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextEvent indicates an expected call of GetNextEvent.
func (mr *MockEventReaderMockRecorder) GetNextEvent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextEvent", reflect.TypeOf((*MockEventReader)(nil).GetNextEvent))
}

// MockPlayerRepository is a mock of PlayerRepository interface.
type MockPlayerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerRepositoryMockRecorder
	isgomock struct{}
}

// MockPlayerRepositoryMockRecorder is the mock recorder for MockPlayerRepository.
type MockPlayerRepositoryMockRecorder struct {
	mock *MockPlayerRepository
}

// NewMockPlayerRepository creates a new mock instance.
func NewMockPlayerRepository(ctrl *gomock.Controller) *MockPlayerRepository {
	mock := &MockPlayerRepository{ctrl: ctrl}
	mock.recorder = &MockPlayerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerRepository) EXPECT() *MockPlayerRepositoryMockRecorder {
	return m.recorder
}

// AddPlayer mocks base method.
func (m *MockPlayerRepository) AddPlayer(ctx context.Context, p core.Player) (core.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPlayer", ctx, p)
	ret0, _ := ret[0].(core.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPlayer indicates an expected call of AddPlayer.
func (mr *MockPlayerRepositoryMockRecorder) AddPlayer(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPlayer", reflect.TypeOf((*MockPlayerRepository)(nil).AddPlayer), ctx, p)
}

// GetAllPlayers mocks base method.
func (m *MockPlayerRepository) GetAllPlayers(ctx context.Context) []core.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPlayers", ctx)
	ret0, _ := ret[0].([]core.Player)
	return ret0
}

// GetAllPlayers indicates an expected call of GetAllPlayers.
func (mr *MockPlayerRepositoryMockRecorder) GetAllPlayers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPlayers", reflect.TypeOf((*MockPlayerRepository)(nil).GetAllPlayers), ctx)
}

// GetPlayerById mocks base method.
func (m *MockPlayerRepository) GetPlayerById(ctx context.Context, id int) (core.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayerById", ctx, id)
	ret0, _ := ret[0].(core.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayerById indicates an expected call of GetPlayerById.
func (mr *MockPlayerRepositoryMockRecorder) GetPlayerById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayerById", reflect.TypeOf((*MockPlayerRepository)(nil).GetPlayerById), ctx, id)
}

// UpdatePlayer mocks base method.
func (m *MockPlayerRepository) UpdatePlayer(ctx context.Context, p core.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlayer", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlayer indicates an expected call of UpdatePlayer.
func (mr *MockPlayerRepositoryMockRecorder) UpdatePlayer(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlayer", reflect.TypeOf((*MockPlayerRepository)(nil).UpdatePlayer), ctx, p)
}

// MockPrinter is a mock of Printer interface.
type MockPrinter struct {
	ctrl     *gomock.Controller
	recorder *MockPrinterMockRecorder
	isgomock struct{}
}

// MockPrinterMockRecorder is the mock recorder for MockPrinter.
type MockPrinterMockRecorder struct {
	mock *MockPrinter
}

// NewMockPrinter creates a new mock instance.
func NewMockPrinter(ctrl *gomock.Controller) *MockPrinter {
	mock := &MockPrinter{ctrl: ctrl}
	mock.recorder = &MockPrinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrinter) EXPECT() *MockPrinterMockRecorder {
	return m.recorder
}

// PrintEventCannotContinue mocks base method.
func (m *MockPrinter) PrintEventCannotContinue(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventCannotContinue", e)
}

// PrintEventCannotContinue indicates an expected call of PrintEventCannotContinue.
func (mr *MockPrinterMockRecorder) PrintEventCannotContinue(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventCannotContinue", reflect.TypeOf((*MockPrinter)(nil).PrintEventCannotContinue), e)
}

// PrintEventDamaged mocks base method.
func (m *MockPrinter) PrintEventDamaged(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventDamaged", e)
}

// PrintEventDamaged indicates an expected call of PrintEventDamaged.
func (mr *MockPrinterMockRecorder) PrintEventDamaged(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventDamaged", reflect.TypeOf((*MockPrinter)(nil).PrintEventDamaged), e)
}

// PrintEventDead mocks base method.
func (m *MockPrinter) PrintEventDead(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventDead", e)
}

// PrintEventDead indicates an expected call of PrintEventDead.
func (mr *MockPrinterMockRecorder) PrintEventDead(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventDead", reflect.TypeOf((*MockPrinter)(nil).PrintEventDead), e)
}

// PrintEventDisqualified mocks base method.
func (m *MockPrinter) PrintEventDisqualified(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventDisqualified", e)
}

// PrintEventDisqualified indicates an expected call of PrintEventDisqualified.
func (mr *MockPrinterMockRecorder) PrintEventDisqualified(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventDisqualified", reflect.TypeOf((*MockPrinter)(nil).PrintEventDisqualified), e)
}

// PrintEventEnter mocks base method.
func (m *MockPrinter) PrintEventEnter(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventEnter", e)
}

// PrintEventEnter indicates an expected call of PrintEventEnter.
func (mr *MockPrinterMockRecorder) PrintEventEnter(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventEnter", reflect.TypeOf((*MockPrinter)(nil).PrintEventEnter), e)
}

// PrintEventEnterBoss mocks base method.
func (m *MockPrinter) PrintEventEnterBoss(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventEnterBoss", e)
}

// PrintEventEnterBoss indicates an expected call of PrintEventEnterBoss.
func (mr *MockPrinterMockRecorder) PrintEventEnterBoss(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventEnterBoss", reflect.TypeOf((*MockPrinter)(nil).PrintEventEnterBoss), e)
}

// PrintEventHealed mocks base method.
func (m *MockPrinter) PrintEventHealed(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventHealed", e)
}

// PrintEventHealed indicates an expected call of PrintEventHealed.
func (mr *MockPrinterMockRecorder) PrintEventHealed(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventHealed", reflect.TypeOf((*MockPrinter)(nil).PrintEventHealed), e)
}

// PrintEventImpossibleMove mocks base method.
func (m *MockPrinter) PrintEventImpossibleMove(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventImpossibleMove", e)
}

// PrintEventImpossibleMove indicates an expected call of PrintEventImpossibleMove.
func (mr *MockPrinterMockRecorder) PrintEventImpossibleMove(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventImpossibleMove", reflect.TypeOf((*MockPrinter)(nil).PrintEventImpossibleMove), e)
}

// PrintEventKillBoss mocks base method.
func (m *MockPrinter) PrintEventKillBoss(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventKillBoss", e)
}

// PrintEventKillBoss indicates an expected call of PrintEventKillBoss.
func (mr *MockPrinterMockRecorder) PrintEventKillBoss(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventKillBoss", reflect.TypeOf((*MockPrinter)(nil).PrintEventKillBoss), e)
}

// PrintEventKillMonster mocks base method.
func (m *MockPrinter) PrintEventKillMonster(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventKillMonster", e)
}

// PrintEventKillMonster indicates an expected call of PrintEventKillMonster.
func (mr *MockPrinterMockRecorder) PrintEventKillMonster(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventKillMonster", reflect.TypeOf((*MockPrinter)(nil).PrintEventKillMonster), e)
}

// PrintEventLeft mocks base method.
func (m *MockPrinter) PrintEventLeft(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventLeft", e)
}

// PrintEventLeft indicates an expected call of PrintEventLeft.
func (mr *MockPrinterMockRecorder) PrintEventLeft(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventLeft", reflect.TypeOf((*MockPrinter)(nil).PrintEventLeft), e)
}

// PrintEventNextFloor mocks base method.
func (m *MockPrinter) PrintEventNextFloor(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventNextFloor", e)
}

// PrintEventNextFloor indicates an expected call of PrintEventNextFloor.
func (mr *MockPrinterMockRecorder) PrintEventNextFloor(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventNextFloor", reflect.TypeOf((*MockPrinter)(nil).PrintEventNextFloor), e)
}

// PrintEventPrevFloor mocks base method.
func (m *MockPrinter) PrintEventPrevFloor(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventPrevFloor", e)
}

// PrintEventPrevFloor indicates an expected call of PrintEventPrevFloor.
func (mr *MockPrinterMockRecorder) PrintEventPrevFloor(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventPrevFloor", reflect.TypeOf((*MockPrinter)(nil).PrintEventPrevFloor), e)
}

// PrintEventRegister mocks base method.
func (m *MockPrinter) PrintEventRegister(e core.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintEventRegister", e)
}

// PrintEventRegister indicates an expected call of PrintEventRegister.
func (mr *MockPrinterMockRecorder) PrintEventRegister(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintEventRegister", reflect.TypeOf((*MockPrinter)(nil).PrintEventRegister), e)
}
